Error using radStringPicker and radPicker
When I try to use radStringPicker and radPicker I got the Exception: java.lang.ClassCastException - java.lang.String cannot be cast to java.util.Date
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Date

I found that in the class PickerPropertyViewBuilder does not have the option to set a String Picker.